login_:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
